//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRepositorio.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Agenda {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Agenda() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGRepositorio.Resource.Agenda", typeof(Agenda).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into AgendaServico (IdAgenda,IdServico) values (@IdAgenda,@IdServico).
        /// </summary>
        internal static string AgendaServicoAdd {
            get {
                return ResourceManager.GetString("AgendaServicoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from agendaservico where idagenda = @IdAgenda.
        /// </summary>
        internal static string AgendaServicoDel {
            get {
                return ResourceManager.GetString("AgendaServicoDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Agenda]
        ///   SET [IdProfissional] = @IdProfissional
        ///      ,[IdCliente] = @IdCliente
        ///      ,[Data] = @Data
        ///      ,[HoraInicial] = @HoraInicial
        ///      ,[HoraFinal] = @HoraFinal
        ///      ,[Situacao] = @Situacao
        ///      ,[Complemento] = @Complemento
        /// WHERE Agenda.IdAgenda = @IdAgenda.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Agenda]
        ///           ([IdProfissional]
        ///           ,[IdCliente]
        ///           ,[Data]
        ///           ,[HoraInicial]
        ///           ,[HoraFinal]
        ///           ,[Situacao]
        ///           ,[Complemento])
        ///     VALUES
        ///           (@IdProfissional
        ///           ,@IdCliente
        ///           ,@Data
        ///           ,@HoraInicial
        ///           ,@HoraFinal
        ///           ,@Situacao
        ///           ,@Complemento); select SCOPE_IDENTITY();.
        /// </summary>
        internal static string Inserir {
            get {
                return ResourceManager.GetString("Inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select	A.IdAgenda as AIdAgenda,
        ///		A.Data as AData,
        ///		A.HoraFinal as AHoraFinal,
        ///		A.HoraInicial as AHoraInicial,
        ///		A.Situacao as ASituacao,
        ///		A.Complemento as AComplemento,
        ///		p.IdProfissional as PIdProfissional,
        ///		P.Nome as PNome,
        ///		P.Telefone as PTelefone,
        ///		p.Celular as PCelular,
        ///		C.IdCliente as CIdCliente,
        ///		C.Nome as CNome,
        ///		c.Telefone as CTelefone,
        ///		c.Celular as CCelular
        ///from Agenda A
        ///inner join Profissional p ON a.IdProfissional = p.IdProfissional
        ///inner join Cliente c ON A.IdCliente [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Recuperar {
            get {
                return ResourceManager.GetString("Recuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select	A.IdAgenda as AIdAgenda,
        ///		A.Data as AData,
        ///		A.HoraFinal as AHoraFinal,
        ///		A.HoraInicial as AHoraInicial,
        ///		A.Situacao as ASituacao,
        ///		A.Complemento as AComplemento,
        ///		p.IdProfissional as PIdProfissional,
        ///		P.Nome as PNome,
        ///		P.Telefone as PTelefone,
        ///		p.Celular as PCelular,
        ///		C.IdCliente as CIdCliente,
        ///		C.Nome as CNome,
        ///		c.Telefone as CTelefone,
        ///		c.Celular as CCelular
        ///from Agenda A
        ///inner join Profissional p ON a.IdProfissional = p.IdProfissional
        ///inner join Cliente c ON A.IdCliente [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecuperarLista {
            get {
                return ResourceManager.GetString("RecuperarLista", resourceCulture);
            }
        }
    }
}
