//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRepositorio.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cliente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cliente() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGRepositorio.Resource.Cliente", typeof(Cliente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Cliente]([Nome],[Telefone],[Celular],[Endereco],[Cidade],[Bairro],[CPF],[Email],[Numero], [Status])
        ///VALUES(@Nome,@Telefone,@Celular,@Endereco,@Cidade,@Bairro,@CPF,@Email,@Numero,@Status).
        /// </summary>
        internal static string Inserir {
            get {
                return ResourceManager.GetString("Inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IdCliente, Nome, Telefone, Celular, Endereco, Cidade, Bairro, CPF, Email, Numero,Status FROM Cliente where IdCliente = @IdCliente.
        /// </summary>
        internal static string Recuperar {
            get {
                return ResourceManager.GetString("Recuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IdCliente, Nome, Telefone, Celular, Endereco, Cidade, Bairro, CPF, Email, Numero,Status FROM Cliente.
        /// </summary>
        internal static string RecuperarLista {
            get {
                return ResourceManager.GetString("RecuperarLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente 
        ///SET Status = @Status WHERE IdCliente = @IdCliente.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente 
        ///SET Nome = @Nome,Telefone = @Telefone,Celular= @Celular,Endereco = @Endereco,
        ///Cidade = @Cidade,Bairro = @Bairro,CPF = @CPF,Email= @Email,Numero = @Numero,Status = @Status
        ///WHERE IdCliente = @IdCliente.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
