//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRepositorio.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Profissional {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profissional() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGRepositorio.Resource.Profissional", typeof(Profissional).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profissional Set Status = @Status where IdProfissional = @IdProfissional.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Profissional] ([Nome],[Telefone],[Celular],[Endereco],[Numero],[Cidade],[Bairro],[ParticipaAgenda],[Email],[Nascimento],[Status])
        ///     VALUES(@Nome,@Telefone,@Celular,@Endereco,@Numero,@Cidade,@Bairro,@ParticipaAgenda,@Email,@Nascimento,@Status).
        /// </summary>
        internal static string Inserir {
            get {
                return ResourceManager.GetString("Inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [IdProfissional]
        ///      ,[Nome]
        ///      ,[Telefone]
        ///      ,[Celular]
        ///      ,[Endereco]
        ///      ,[Numero]
        ///      ,[Cidade]
        ///      ,[Bairro]
        ///      ,[ParticipaAgenda]
        ///      ,[Email]
        ///      ,[Nascimento]
        ///      ,[Status]
        ///  FROM [dbo].[Profissional] where Profissional.IdProfissional = @IdProfissional.
        /// </summary>
        internal static string Recuperar {
            get {
                return ResourceManager.GetString("Recuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [IdProfissional]
        ///      ,[Nome]
        ///      ,[Telefone]
        ///      ,[Celular]
        ///      ,[Endereco]
        ///      ,[Numero]
        ///      ,[Cidade]
        ///      ,[Bairro]
        ///      ,[ParticipaAgenda]
        ///      ,[Email]
        ///      ,[Nascimento]
        ///      ,[Status]
        ///  FROM [dbo].[Profissional].
        /// </summary>
        internal static string RecuperarLista {
            get {
                return ResourceManager.GetString("RecuperarLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [IdProfissional]
        ///      ,[Nome]
        ///      ,[Telefone]
        ///      ,[Celular]
        ///      ,[Endereco]
        ///      ,[Numero]
        ///      ,[Cidade]
        ///      ,[Bairro]
        ///      ,[ParticipaAgenda]
        ///      ,[Email]
        ///      ,[Nascimento]
        ///      ,[Status]
        ///  FROM [dbo].[Profissional] where Profissional.ParticipaAgenda = @ParticipaAgenda.
        /// </summary>
        internal static string RecuperarListaAgenda {
            get {
                return ResourceManager.GetString("RecuperarListaAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Profissional]
        ///   SET [Nome] = @Nome
        ///      ,[Telefone] = @Telefone
        ///      ,[Celular] = @Celular
        ///      ,[Endereco] = @Endereco
        ///      ,[Numero] = @Numero
        ///      ,[Cidade] = @Cidade
        ///      ,[Bairro] = @Bairro
        ///      ,[ParticipaAgenda] = @ParticipaAgenda
        ///      ,[Email] = @Email
        ///      ,[Nascimento] = @Nascimento
        ///      ,[Status] = @Status
        /// WHERE Profissional.IdProfissional = @IdProfissional.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
